# Class Lab: Discover Association Rules by Apriori Algorithm

## Step 1: setup goal
- use Apriori algorithm to discover association rules

## Step 2: retrieve data

In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from pathlib import Path
source_path = Path.cwd() / '..' / 'csv' / 'market_dummy_data.csv'
df = pd.read_csv(source_path)
df

    ID    Item  Quantity
0   T1    Milk         1
1   T1   Bread         2
2   T1  Butter         1
3   T2    Beer         3
4   T3    Milk         4
5   T3    Beer         5
6   T3  Butter         1
7   T4    Milk         1
8   T4   Bread         4
9   T4    Beer         3
10  T5    Milk         5
11  T5   Bread         1
12  T5  Butter         1

## Step 3: prepare data

In [3]:
basket = pd.pivot_table(data=df, index='ID', columns='Item', values='Quantity', aggfunc='sum', fill_value=0)
basket

Item  Beer  Bread  Butter  Milk
ID
T1       0      2       1     1
T2       3      0       0     0
T3       5      0       1     4
T4       3      4       0     1
T5       0      1       1     5

In [4]:
def convert_into_binary(x): # 將購買數量轉換成0/1
    if x >= 1:
        return True
    else:
        return False

basket_set = basket.map(convert_into_binary)
basket_set

Item   Beer  Bread  Butter   Milk
ID
T1    False   True    True   True
T2     True  False   False  False
T3     True  False    True   True
T4     True   True   False   True
T5    False   True    True   True

## Step 4: explore data

In [4]:
# Find frequent itemsets
freq_itemsets = apriori(basket_set, min_support=0.4, use_colnames=True)
freq_itemsets.sort_values(by='support', ascending=False)

   support               itemsets
3      0.8                 (Milk)
0      0.6                 (Beer)
1      0.6                (Bread)
2      0.6               (Butter)
6      0.6          (Bread, Milk)
7      0.6         (Milk, Butter)
4      0.4           (Milk, Beer)
5      0.4        (Bread, Butter)
8      0.4  (Bread, Butter, Milk)

## Step 5: build model
Comparing the accuracy of the original data set with latent variables

In [5]:
# Generate association rules
min_conf = 0.7
rules = association_rules(freq_itemsets, metric="confidence", min_threshold=min_conf)
rules[["antecedents", "consequents", "support", "confidence", "lift"]]

       antecedents consequents  support  confidence  lift
0          (Bread)      (Milk)      0.6        1.00  1.25
1           (Milk)     (Bread)      0.6        0.75  1.25
2           (Milk)    (Butter)      0.6        0.75  1.25
3         (Butter)      (Milk)      0.6        1.00  1.25
4  (Bread, Butter)      (Milk)      0.4        1.00  1.25

## Step 6: presentation - Marketing Decision Recommendations