In [1]:
from pathlib import Path
import pandas as pd

# Load file

In [3]:
source_file = Path.cwd() / '../csv/shoe_size.csv'
df = pd.read_csv(source_file)
# adjust column names to be more pythonic
df = df.rename(columns={
    'ID': 'id',
    'Gender': 'gender', 
    'Height_cm': 'height_cm',
    'Weight_kg': 'weight_kg',
    'Shoe size_cm': 'shoe_size_cm'
})

# alternative way to rename columns
# df.columns = df.columns.str.replace('ID', 'id')
# df.columns = df.columns.str.replace('Gender', 'gender')

df.head()

   id  gender  height_cm  weight_kg  shoe_size_cm
0   1    Male      175.0       83.0          28.0
1   2    Male      195.0      112.0          31.0
2   3    Male      175.0       90.0          28.5
3   4  Female      154.0       58.0          22.5
4   5  Female      154.0       58.0          22.5

# Check and drop duplicates

In [4]:
df.shape

(10009, 5)

In [5]:
df[df.duplicated()] # 顯示重複的 rows
df[df.duplicated(keep=False)] # 顯示所有重複的 rows
df.drop_duplicates(inplace=True)
df.shape

(10000, 5)

# Check null values

In [7]:
df.isnull().sum()

id               0
gender           0
height_cm        5
weight_kg       10
shoe_size_cm    15
dtype: int64

In [8]:
# height_cm欄有5個null值，我們可以用其他的gender, shoe_size_cm 的平均值來補足height_cm的值
df[df['height_cm'].isnull()] # 顯示 height_cm 欄有空值的 rows
df[df['height_cm'].isnull()].index # row: 12, 53, 858, 899, 953)

df['height_cm'] = df['height_cm'].fillna(value = df.groupby(['gender', 'weight_kg', 'shoe_size_cm'])['height_cm'].transform('mean'))

df.loc[[12, 53, 858, 899, 953], :]
df[df['height_cm'].isnull()]

Empty DataFrame
Columns: [id, gender, height_cm, weight_kg, shoe_size_cm]
Index: []

In [9]:
# weight_kg欄有10個null值，我們可以用其他的gender, shoe_size_cm 的平均值來補足height_cm的值
df[df['weight_kg'].isnull()] # 顯示 height_cm 欄有空值的 rows
df[df['weight_kg'].isnull()].index # row: [202, 316, 350, 384, 432, 504, 695, 712, 730, 759]

# df.groupby(['gender','height_cm', 'shoe_size_cm'])['weight_kg'].mean()

df['weight_kg'] = df['weight_kg'].fillna(value = df.groupby(['gender', 'height_cm', 'shoe_size_cm'])['weight_kg'].transform('mean'))

df.loc[[202, 316, 350, 384, 432, 504, 695, 712, 730, 759], :]
df[df['weight_kg'].isnull()]

Empty DataFrame
Columns: [id, gender, height_cm, weight_kg, shoe_size_cm]
Index: []

In [10]:
df[df['shoe_size_cm'].isnull()] # 顯示 shoe_size_cm 欄有空值的 rows
df.dropna(axis=0, inplace=True)
df.isnull().sum()

id              0
gender          0
height_cm       0
weight_kg       0
shoe_size_cm    0
dtype: int64

In [11]:
df.head()

   id  gender  height_cm  weight_kg  shoe_size_cm
0   1    Male      175.0       83.0          28.0
1   2    Male      195.0      112.0          31.0
2   3    Male      175.0       90.0          28.5
3   4  Female      154.0       58.0          22.5
4   5  Female      154.0       58.0          22.5

In [13]:
df_copy = df.copy()
df['gender'] = df['gender'].map({'Male': 1, 'Female': 0})
df['gender'] = df['gender'].astype('int')
df['height_cm'] = df['height_cm'].astype('int')
df['weight_kg'] = df['weight_kg'].astype('int')
df['shoe_size_cm'] = df['shoe_size_cm'].astype('int')
df['id'] = df['id'].astype('str')
df.head()
df.set_index('id', inplace=True)

df.dtypes

gender          int64
height_cm       int64
weight_kg       int64
shoe_size_cm    int64
dtype: object

In [14]:
df.head(10)

    gender  height_cm  weight_kg  shoe_size_cm
id
1        1        175         83            28
2        1        195        112            31
3        1        175         90            28
4        0        154         58            22
5        0        154         58            22
6        1        180         93            29
7        1        177         87            28
8        0        167         70            24
9        1        172         77            28
10       0        152         57            22